cluster:
  name: "nodejs-example23234secf"
  provider: "google"
  google_project: "gabo-project"
  google_node_count: 2
  google_gke_version: "1.9.6-gke.1"
  secret_id: "444a6010-a6a5-4510-a465-e9d2719887af"

# generic Banzai Cloud `spotguide` for a nodejs application
pipeline:
# this step builds and uploads the application image to the image registry (docker)
  build_container:
    image: plugins/docker
    dockerfile: Dockerfile
    repo: banzaicloud/nodejs-example
    tags: "{{ printf \"dev-%s\" (.DRONE_COMMIT_SHA | trunc 7) }}"
    log: debug
    group: test1234
    pull: true
