cluster:
  name: "drone-nodejs-example-google-6"
  provider: "google"
  secret_id: "c4305cbe-3664-417c-ab7a-e53e102a39a4"

pipeline:
  print_env:
    image: golang:1.10-alpine
    commands:
    - pwd
    - env
    - find .
    - sleep 30
    group: build

  print_env2:
    image: golang:1.10-alpine
    commands:
    - pwd
    - env
    - find .
    - sleep 30
    group: build

  print_env3:
    image: golang:1.10-alpine
    commands:
    - pwd
    - env
    - find .
    - sleep 30
    group: build

  pingpong:
    image: redis
    commands:
      - sleep 5
      - redis-cli -h redis ping
      - redis-cli -h redis set HELLO hello
      - redis-cli -h redis get HELLO

# this step builds and uploads the application image to the image registry (docker)
#   build_container:
#     image: plugins/docker
#     dockerfile: Dockerfile
#     repo: banzaicloud/nandi-test
#     tags: "latest" # {{ printf \"dev-%s\" (.DRONE_COMMIT_SHA | trunc 7) }}
#     log: debug
# secrets: [plugin_endpoint, plugin_token, plugin_username, plugin_password]
# when:
#   event: tag

services:
  redis:
    image: redis
    ports:
    - 6379
  mysql:
    image: mysql
    ports:
    - 3306
    environment:
      MYSQL_ROOT_PASSWORD: "joska"
  while:
    image: busybox
    commands:
    - while true;
  
