cluster:
  name: "drone-nodejs-example-google-6"
  provider: "google"
  secret_id: "c4305cbe-3664-417c-ab7a-e53e102a39a4"

# generic Banzai Cloud `spotguide` for a nodejs application
pipeline:
# this step builds and uploads the application image to the image registry
  build_container:
    image: plugins/docker
    dockerfile: Dockerfile
    repo: banzaicloud/nodejs-example
    tags: "{{ printf \"test-%s\" (.DRONE_COMMIT_SHA | trunc 7) }}"
    log: debug
    pull: true
