cluster:
  name: "drone-nodejs-example-google-6"
  provider: "google"
  secret_id: "c4305cbe-3664-417c-ab7a-e53e102a39a4"

pipeline:
  print_env:
    image: golang:1.10-alpine
    commands:
    - pwd
    - env
    - find .
    - sleep 30
    group: build

  print_env2:
    image: golang:1.10-alpine
    commands:
    - pwd
    - env
    - find .
    - sleep 30
    group: build

  print_env3:
    image: golang:1.10-alpine
    commands:
    - pwd
    - env
    - find .
    - sleep 30
    group: build

services:
  redis:
    image: redis
    ports:
    - 6379
